# Generated by Django 4.1.2 on 2022-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expiry', models.DateField(blank=True)),
                ('time_left', models.DateField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
