# Generated by Django 4.1.2 on 2022-10-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_med_rename_posts_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='time_left',
        ),
    ]
