# Generated by Django 4.1.2 on 2022-10-12 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_med_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='time_left',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 13)),
        ),
    ]
