# Generated by Django 4.1.2 on 2022-10-12 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_med_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 13)),
        ),
        migrations.AlterField(
            model_name='med',
            name='time_left',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
