# Generated by Django 4.1.2 on 2022-10-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_med_date_alter_med_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='med',
            name='date',
        ),
    ]
