# Generated by Django 4.1.2 on 2022-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_med_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='med',
            name='green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='med',
            name='red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='med',
            name='yellow',
            field=models.BooleanField(default=False),
        ),
    ]
