# Generated by Django 4.1.2 on 2022-10-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_med_green_med_red_med_yellow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
